# Dependencies
markdown:                               kramdown
highlighter:                            pygments

# Permalinks
permalink:                              /:categories/:title/
relative_permalinks:                    true

# Setup
title:                                  tail call
tagline:                                'Ramblings in software development'
description:                            The ramblings of a 25-year-old software developer from Germany.
url:                                    https://blog.kempkens.io
baseurl:                                /

author:
  name:                                 'Daniel Kempkens'
  url:                                  https://kempkens.io
  email:                                daniel+blog@kempkens.io

paginate:                               5

include:                                [".htaccess"]
exclude:                                ["tmp", "Gemfile", "Gemfile.lock", "Makefile"]

# Custom
disqus_shortname: blog-kempkens-io
