title:            tail call
description:      '[...] procedure calls may be usefully thought of as GOTO statements [...]'
disqus_shortname: blog-kempkens-io
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://blog.kempkens.io
source_url:       https://github.com/nifoc/blog.kempkens.io

# Owner/author information
owner:
  name:           Daniel Kempkens
  avatar:         sidebar/avatar.jpg
  bio:            "I'm a 24-year-old software developer from Germany."
  email:          daniel+blog@kempkens.io
  # Social networking links used in footer. Update and remove as you like.
  twitter: nifoc_
  app_net: nifoc
  facebook:
  github: nifoc
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:
  keybase: nifoc

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-28082386-3
google_analytics_linker:
  'daniel.xxx':
    - blog.kempkens.io
  'blog.kempkens.io':
    - daniel.xxx
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Berlin
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

assets:
  cache: true
  js_compressor:  uglifier
  css_compressor: yui

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
